### ISSUE TITLE
Notes are all unsnapped on latest release

### ISSUE THREAD

**Issue by Adrriii** [IceDynamix/qua3osu#2]
After using resnap tool in Quaver to have all notes correctly snapped, converting to osu and opening AImod shows all (or nearly all) notes as unsnapped

**Comment by IceDynamix** [comment]
I'm not sure how osu considers notes as being snapped or not, I assumed it was the same but that's not the case. Maybe it's because of float/double inaccuracies? Maybe it *is* the same but it's shifted by a few milliseconds or two? I don't know, and I can't really be bothered to fix this. The purpose of the converter isn't to make a perfect conversion, but to provide a solid base to work off, after all. You won't notice the unsnaps in gameplay, and that's good enough for me. Update this issue if you know what exactly causes this.
